"""initial migration2

Revision ID: b07acca15809
Revises: bcc9d155e4a4
Create Date: 2024-11-18 00:05:19.068945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07acca15809'
down_revision: Union[str, None] = 'bcc9d155e4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'failed_count')
    op.drop_column('entry', 'success_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('success_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
